version: '3.8'

services:
  em-service:
    container_name: em-service
    image: em-service
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - EM_PERSISTENCE_SERVICE_URL=http://em-persistence-service:8887
    networks:
      - app-network

  em-persistence-service:
    container_name: em-persistence-service
    image: em-persistence-service
    build:
      context: ../em-persistence-service
    ports:
      - "8887:8887"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
